services:
  api:
    build: .
    container_name: minha-api
    ports:
      - "4000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=daniel
      - DB_PASSWORD=0099abc
      - DB_NAME=banco
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: meu-postgresd
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vitor032010
      - POSTGRES_DB=banco
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  pgdata:
